### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by jaortisi6** [devontehillman/Project_2#6]
**AS A** bilingual blogger
**I WANT** distribute my content to my readers in my preferred language
**WHILE ALSO** allowing readers of other languages to view my product in their preferred language
**SO THAT** my product can reach a wider audience and allow me to connect with people all over the world

**Comment by devontehillman** [comment]
Explanation
This is a blog web site that has one author and many content consumers. As the author of the web site you can add, read, edit, and delete blogs. When the author creates there articles it is defaulted in english and then taken and translated into four additional languages via an api call and then results are stored into our database. As a user I can select from categories to sort out articles. Once the user opens an article they can select which language to have the article displayed in.

**Comment by devontehillman** [comment]
Possible future development
 * login to the site and save articles and preferred language, like and comment on articles.

**Comment by JGreenOS** [comment]
Added to Readme
