### ISSUE TITLE
Acceptance Criteria

### ISSUE THREAD

**Issue by jaortisi6** [devontehillman/Project_2#7]
**GIVEN** a blog site
**WHEN** a user logs into the app
**THEN** they are able to add, read, delete blog posts
**WHEN** a user chooses to add
**THEN** they are brought to a new blog post screen
**WHEN** a user chooses to read
**THEN** they are presented with a page of existing blog posts
**WHEN** a user chooses a category
**THEN** posts pertaining to their selected category are displayed
**WHEN** a user chooses to delete
**THEN** they are presented a page of their existing blog posts, so they can choose which one to delete

--------------------------------------------------------------------------------------------------------------------------

**WHEN** users who are not the author view the blog site
**THEN** they can select categories, or view all blog posts

**Comment by JGreenOS** [comment]
Added to Readme
